---
title: "Model Selection"
author: "Shiwani Sapkota"
date: "2023-04-07"
output: html_document
---

LOADING REQUIRED PACKAGES

```{r, warning = FALSE}
library(here)
library(tidyverse)
library(tidymodels)
library(ggplot2)
library(ranger)
library(rpart)
library(glmnet)
library(vip)
library(rpart.plot)
library(performance)
library(yardstick)
library(recipes)
```

LOADING DATA

```{r}
# Reading the cleaned rds file
data_clean <- readRDS(here("data", "processed_cleaned_data", "mammogram_ses_clean.rds"))
glimpse(data_clean)

# Creating a new object to work with for the analysis
data_clean_main <- data_clean

# Making sure there are no missing values in any variables
any(is.na(data_clean_main))

# Changing class of mammogram_status variable from integer to factor as we can't use mammogram_status (main outcome) as an integer while preparing recipe and training the model
class(data_clean_main$mammogram_status)
data_clean_main$mammogram_status <- as.factor(data_clean_main$mammogram_status)
data_clean_main$year <- as.factor(data_clean_main$year)
data_clean_main$age <- as.factor(data_clean_main$age)
data_clean_main$hispanic_status <- as.factor(data_clean_main$hispanic_status)
data_clean_main$income <- as.factor(data_clean_main$income)
data_clean_main$education <- as.factor(data_clean_main$education)
data_clean_main$marital_status <- as.factor(data_clean_main$marital_status)
data_clean_main$insurance_status <- as.factor(data_clean_main$insurance_status)
data_clean_main$health_status <- as.factor(data_clean_main$health_status)
data_clean_main$usual_medicalcare_status <- as.factor(data_clean_main$usual_medicalcare_status)
data_clean_main$smoking_status <- as.factor(data_clean_main$smoking_status)
data_clean_main$alcohol_status <- as.factor(data_clean_main$alcohol_status)
data_clean_main$diabetes_status <- as.factor(data_clean_main$diabetes_status)
```

**DATA SETUP**

```{r}
# Setting the random seed to 123
set.seed(123)

# Splitting dataset into 70% training and 30% testing and using mammogram status outcome as stratification
data_split <- initial_split(data_clean_main, prop = 7/10, strata = mammogram_status)
  
# Creating data frames for the two sets
train_data <- training(data_split)
test_data  <- testing(data_split)

# Creating 5-fold cross-validation, 5 times repeated
CV_fold_data <- vfold_cv(train_data, v = 5, repeats = 5, strata = mammogram_status)

# Creating a recipe
recipe_data <- recipe(mammogram_status ~ year + age + hispanic_status + income + education + marital_status + region_residence + insurance_status + health_status + usual_medicalcare_status + smoking_status + alcohol_status + diabetes_status, data = train_data) %>%
  step_dummy(all_nominal(), -all_outcomes())
```

**NULL MODEL PERFORMANCE**

```{r}
# Using train data
# Creating a recipe for null model
recipe_null_train <- recipe(mammogram_status ~ 1, data = train_data) %>%
  step_dummy(all_nominal(), -all_outcomes())

# Creating a logistic model recipe
recipe_null_logistic <- logistic_reg() %>% 
  set_engine("glm") %>% 
  set_mode("classification")

# Creating workflow pairing model and recipe 
workflow_null_train <- workflow() %>% 
  add_model(recipe_null_logistic) %>% 
  add_recipe(recipe_null_train)

# Fitting null model with the folds created from train data 
train_null <- fit_resamples(workflow_null_train, resamples = CV_fold_data)

# Computing RMSE for train data
metrics_null_train <- collect_metrics(train_null)
metrics_null_train
```

From the null model, we got ROC AUC as 0.5.