---
title: "Supplement to Manuscript for MADA Project"
subtitle: "Supplement Materials"
author: Shiwani Sapkota
date: "`r Sys.Date()`"
format:
  pdf:
    toc: false
    number-sections: true
    highlight-style: github
bibliography: ../../dataanalysis_template_references.bib
csl: ../../vancouver.csl
---

```{r, echo=FALSE, message=FALSE}
# load a few R packages
library(knitr)
library(ipumsr)
library(readr)
library(skimr)
library(tidyverse)
library(dplyr)
library(survey)
library(naniar)
library(gmodels) #for ch-sq frequency table
library(vcd) # for three way frequency table
library(gtsummary)
library(openxlsx)
library(ggplot2)
library(ggthemes)
```

# Overview

In this supplement file, you can find details about the data file extraction and codes involved in the process of data extraction and data analysis.

# Code and file information

```{r}
# Skip this code chunk if you already have `mammogram_ses1.rds` raw data file
# NHIS provides .xml and .dat file while extracting the data from website
# Commenting these codes as they were used for data extraction and data preparation process which are needed to be done only once before preparing the data file

# Preparing and loading the raw data file and saving as .csv and .rds files
# ddi <- read_ipums_ddi("nhis_00003.xml")
# data <- read_ipums_micro(ddi)

# Saving the raw data file as .csv file and commenting out this code so it does not get created everytime we run this code chunk
# readr::write_csv(data, "mammogram_ses.csv")

# It seems the created csv file is very large (153 MB) and GitKraken won't like it so lets create an rds file so that could be of small size

# Saving the raw data file as .rds file and commenting out this code so it does not get created everytime we run this code chunk
# saveRDS(data, "mammogram_ses1.rds")

# From here, you can follow general steps involved in data analysis and the
# respective codes are documented in the respected folders of this project:
# 1. Data cleaning
# 2. Exploratory Data analysis
# 3. Main statistical analysis
```

## Additional result

```{r}
#| label: Additional Table 1
#| tbl-cap: "Fit table using mammogram status as the outcome and age & hispanic_status as predictors."
#| echo: FALSE
additionaltable1 = readRDS(here("results", "statistical_analysis_result", "age_hispanic_model.rds"))
knitr::kable(additionaltable1)
```

```{r}
#| label: Additional Table 2
#| tbl-cap: "Fit table using mammogram status as the outcome and demographic characteristics variables as predictors."
#| echo: FALSE
additionaltable2 = readRDS(here("results", "statistical_analysis_result", "demographic_model.rds"))
knitr::kable(additionaltable2)
```

```{r}
#| label: Additional Table 3
#| tbl-cap: "Fit table using mammogram status as the outcome and the medical characteristics as the predictors."
#| echo: FALSE
additionaltable1 = readRDS(here("results", "statistical_analysis_result", "medical_model.rds"))
knitr::kable(additionaltable3)
```

```{r}
#| label: Additional Table 4
#| tbl-cap: "Fit table using mammogram status as the outcome and smoking & alcohol characteristics as the predictors."
#| echo: FALSE
additionaltable1 = readRDS(here("results", "statistical_analysis_result", "smoking_alcohol_model.rds"))
knitr::kable(additionaltable4)
```

# Discussion

[**To be added]

# References

[**To be added]
